spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:mariadb://localhost:3332
    user: ${DB_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  datasource:
    url: jdbc:mariadb://localhost:3332/chicken
    username: ${DB_USER}
    password: ${MYSQL_ROOT_PASSWORD}