version: "3.1"
services:
  database:
    image: mariadb:10.5
    ports:
      - "3332:3306"
    env_file:
      - .env
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "DB_USER=${DB_USER}"
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

  spring:
    image: chicken_spring
    build: .
    env_file:
      - .env
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "DB_USER=${DB_USER}"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
      - "TUTOREN=${TUTOREN}"
      - "ORGANISATOREN=${ORGANISATOREN}"
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database