version: "3.8"
services:
  database:
    image: mariadb:10.7
    ports:
      - "3306:3306" # port binding only for external access via IntelliJ
    env_file: .env
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u$DB_USER', '-p$MARIADB_ROOT_PASSWORD' ]
      timeout: 20s
      interval: 20s
      retries: 10

  spring:
    image: chicken_spring
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
