rollen:
  tutoren: bendisposto
  organisatoren: donald, daisy, minnie, mickey, gundel, dagobert, bendisposto

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
            authorization-grant-type: authorization_code
            scope: user

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token