rollen:
  tutoren: ${TUTOREN}
  organisatoren: ${ORGANISATOREN}

spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:mariadb://localhost:3332
    user: ${DB_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  datasource:
    url: jdbc:mariadb://localhost:3332/chicken
    username: ${DB_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: user

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token